# -*- coding: utf-8 -*-
"""Fibonacci sequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CejFHg1DjY28sP0uXJBM8yAIy-0TtCvN
"""

#print Fibonacci


n = int(input("How many terms? "))

# first two terms
n1, n2 = 0, 1
count = 0

if n <= 0:
   print("Please enter a positive integer")
elif n == 1:
   print("Fibonacci sequence upto",n,":")
   print(n1)
else:
   print("Fibonacci sequence:")
   while count < n:
       print(n1)
       nth = n1 + n2
       n1 = n2
       n2 = nth
       count += 1