# -*- coding: utf-8 -*-
"""Print hello world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CejFHg1DjY28sP0uXJBM8yAIy-0TtCvN
"""

#print hello world
print("Hello world!")